### PR TITLE
- Added performance test and comparison

### PR DESCRIPTION
**Pull request by jcbeyler**
- Added a simplistic driver and time measurement

### CODE REVIEW

**Comment by jcbeyler** [comment]
Currently, I get:

Running wasm with 1000
Time between start/stop is 448683803, average is 448683.803000
Running C with 1000
Time between start/stop is 114830107, average is 114830.107000
Tests passed

so there is work to do, I will study this

**Comment by jerry4chen** [comment]
Sorry for a sudden Quetion, 

I am confused on how to get a libraryLLVM-3.7.0 in order to do the "make" in the Makefile.
so far,
I've built llvm3.7 from srouce on my ubuntu virtual machine 
and the lib folder of llvm3.7 are under the home path.

should  I change the Makefile like :  LIBS = -ly -lfl -L/home/ubuntu/lib -lLLVMcore -lLLVMcodeGen ... 
or should I just set an environment path to the  lib folder of LLVM?
Or is there any clue for me to figure it out?

I've tried for few days, sometimes I get some error message like:  llvm:<something> not declare or wrong path to find the libraries 

Thanks and Best Regards 
Jerry

**Comment by jcbeyler** [comment]
I would use the -L/home/ubuntu/lib solution, it seems the right way of doing it. 

Have you tried changing the path of the llvm library path like you said or not?

**Comment by jerry4chen** [comment]
After I set the path to the home (I've tried that before), it shows a lot of Messages like:
**undefined reference to `llvm::raw_ostream::write(char const*, unsigned long)'**

make2

Am I on the right track if I add all the libLLVM\* stuff into the make file? 
[edit] I know not every of them are used, but I can't figure out which one is used or not, so I will adding all them :p

make3
anyway I will try it now :)

Thanks a lot :)

**Comment by jcbeyler** [comment]
Why did you remove the -lLLVM-3.7.0 ?

You will need that. And why are you trying to link the static libraries? The dynamic ones suffice.

**Comment by ghost** [comment]
I'd be curious to known how to link statically too if you work it out. A quick attempt yielded similar issues using llvm 3.8.

**Comment by jerry4chen** [comment]
because I got : **/usr/bin/ld: cannot find -lLLVM-3.7.0**

for dynamic libraries I only have LLVMLTO.so and LLVMHello.so in the lib folder
lib

**Comment by jcbeyler** [comment]
So you have a problem with the way you compiled it. Either you are not compiling it to have the developer shared library LLVM-3.7.0 or it is somewhere else. That is the shared library you should be going for.

I have not compiled LLVM by hand so I have never played with that (since I just use apt-get). I can try to do it today and see what I get. I'll keep you updated here.

**Comment by ghost** [comment]
It's necessary to configure llvm with --enable-shared to get the libLLVM shared library. Also found it necessary to set the REQUIRES_RTTI=1 environment variable before compiling, to get the rtti. This worked with llvm 3.8:

setenv REQUIRES_RTTI 1
../llvm/configure --prefix <path>/llvm/ --libdir <path>/llvm/lib --disable-terminfo --disable-zlib --enable-targets=host --disable-backtraces --disable-crash-overrides --disable-expensive-checks --enable-introspection --enable-shared --enable-debug-symbols

**Comment by jcbeyler** [comment]
Awesome, thanks for looking into that :); I just use the packages from Ubuntu :)
